baseURL = ""
languageCode = "en-us"
title = "Codejudge | Developer Skill Assessment"
theme = "small-apps"
summaryLength = "10"
paginate = 6

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.carousel.min.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.theme.green.min.css"
  [[params.plugins.css]]
  URL = "plugins/fancybox/jquery.fancybox.min.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/owl-carousel/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "plugins/fancybox/jquery.fancybox.min.js"
  [[params.plugins.js]]
  URL = "plugins/syotimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "Product"
  URL = "/product"
  weight = 2
  
  [[menu.main]]
  name = "Blog"
  URL = "/blog"
  weight = 4

  [[menu.main]]
  name = "team"
  URL = "/team"
  weight = 5
  
  
  [[menu.main]]
  name = "About US"
  URL = "/contact"
  weight = 7

  # footer menu
  [[menu.footer]]
  name = "Product"
  URL = "/about"
  weight = 2
  
  [[menu.footer]]
  name = "Contact"
  URL = "/contact"
  weight = 4
  
  [[menu.footer]]
  name = "Blog"
  URL = "/blog"
  weight = 3



[params]
logo = "images/codejudge.png"
logoAlt = "images/codejudge.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

# footer
  [params.footer]

  # social icon
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-facebook"
  URL = "#"

  [[params.footer.socialIcon]]
  icon = "tf-ion-social-twitter"
  URL = "#"
  
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-instagram"
  URL = "#"

  # call to action
 [params.cta]
  enable = true
  title = "We are hunting Genius Developers"
  content = ""
  btnText = "Join the team"
  URL = "#"
